name: pet_service_application
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  retrofit: ^2.0.1
  dio: ^4.0.0
  logger: ^1.1.0
  json_annotation: ^4.0.1
  webview_flutter: any
  webview_windows: ^0.0.7

  # 라우터 간 화면 전환 효과
  page_transition: ^2.0.4

  # 해시태그 버튼 관리
  # flutter_tags: ^0.4.9+1

  # firebase version // cloud_firestore: firestore 데이터관리
  firebase_auth: ^3.0.1
  firebase_core: ^1.6.0
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.0.3

  # kakao login version
  kakao_flutter_sdk: ^0.7.0
  platform: ^3.0.0
  package_info_plus: ^1.0.4

  # svg 벡터 이미지 사용하기 위함
  flutter_svg: ^0.22.0

  # 갤러리/카메라 이미지 파일 추가에 필요한 라이브러리
  image_cropper: ^1.4.1
  get: ^4.3.8

  # csv file 읽어들이는데 필요한 library
  path_provider: ^2.0.2
  permission_handler: ^7.1.0
  file_picker: ^3.0.4
  csv: ^5.0.0

  # 외부 브라우저 연결
  url_launcher: ^6.0.7

  # 뒤로가기 2번 누르면 종료
  double_back_to_close_app: ^2.0.0

  # 서버 통신을 위한
  http: ^0.13.3

#  # Check that you have this dependency (added in the previous step)
#  firebase_core: ^0.4.0+9
#  # Add the dependency for the FlutterFire plugin for Google Analytics
#  firebase_analytics: ^5.0.2
#  # Add the dependencies for any other Firebase products you want to use in your app
#  # For example, to use Firebase Authentication and Cloud Firestore
#  firebase_auth: ^0.14.0+5
#  cloud_firestore: ^0.12.9+5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  json_serializable: ^4.1.4
  build_runner: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - images/
      - images/bcs/
      - images/bottomBar/
      - images/community/
      - images/loginIcon/
      - images/profile/
      - images/shorts/
      - images/svg/
      - images/product/
      - images/allergyIcon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
